import Head from "next/head";
import Container from "react-bootstrap/Container";
import AppGuides from "@/components/AppGuides";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import ExampleComponents from "@/components/ExampleComponents";

export default function Home() {
  return (
    <>
      <Head>
        <title>Alef Devops</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container as="main" className="py-4 px-3 mx-auto large-text">
        <Header />

        <h2 className="large-heading">
        "O futuro exige transparência, descentralização, autonomia, confiança e segurança"
          </h2>

        <ExampleComponents />

        <hr className="mt-5 mb-4" />

        <AppGuides />
        <Footer />
      </Container>
    </>
  );
}
