import Head from "next/head";

import Container from "react-bootstrap/Container";
import AppGuides from "@/components/AppGuides";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import ExampleComponents from "@/components/ExampleComponents";

const SmartContracts = () => {
  return (
    <>
      <Head>
        <title>Alef Devops</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container as="main" className="py-4 px-3 mx-auto large-text">
        <Header />
        <div style={{
          display: "flex",
          flexDirection: "column",
          //justifyContent: "center",
          alignItems: "center",
          height: "40vh",
          textAlign: "center",
        }}>
          <h1>SmartContracts!</h1>
          <p>Esta página está em construção. Volte em breve!</p>
        </div>
        <Footer />
      </Container>
    </>
  );
};

export default SmartContracts;